// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0rYtRcAD7hO2k4jHHU8nu5Wu9iPrLq9U',
    appId: '1:451432254458:web:6f540352cb83fdb5313243',
    messagingSenderId: '451432254458',
    projectId: 'ssmachat-24e3f',
    authDomain: 'ssmachat-24e3f.firebaseapp.com',
    storageBucket: 'ssmachat-24e3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTN3fN12TfFw1tiiYVHSOIUlv2NP5D9EU',
    appId: '1:451432254458:android:decb5c187b519a04313243',
    messagingSenderId: '451432254458',
    projectId: 'ssmachat-24e3f',
    storageBucket: 'ssmachat-24e3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJrGn9kBp0zP_GUnCll_MvwbDh_pq19E0',
    appId: '1:451432254458:ios:f510ce815b269eef313243',
    messagingSenderId: '451432254458',
    projectId: 'ssmachat-24e3f',
    storageBucket: 'ssmachat-24e3f.appspot.com',
    iosBundleId: 'com.example.videoConferenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJrGn9kBp0zP_GUnCll_MvwbDh_pq19E0',
    appId: '1:451432254458:ios:f510ce815b269eef313243',
    messagingSenderId: '451432254458',
    projectId: 'ssmachat-24e3f',
    storageBucket: 'ssmachat-24e3f.appspot.com',
    iosBundleId: 'com.example.videoConferenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0rYtRcAD7hO2k4jHHU8nu5Wu9iPrLq9U',
    appId: '1:451432254458:web:a521d80ab80eae66313243',
    messagingSenderId: '451432254458',
    projectId: 'ssmachat-24e3f',
    authDomain: 'ssmachat-24e3f.firebaseapp.com',
    storageBucket: 'ssmachat-24e3f.appspot.com',
  );
}
