// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq-ckYxWFlUDnOjbO2ZtJiVoPi9OcTaR4',
    appId: '1:64446242342:web:3936c6c9736f7a386fd0e7',
    messagingSenderId: '64446242342',
    projectId: 'ssmachat',
    authDomain: 'ssmachat.firebaseapp.com',
    storageBucket: 'ssmachat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArT4h_PGR6DiBLAJJ1v_7uKLOYiE5mUlI',
    appId: '1:64446242342:android:a32b3a6ab8ed90876fd0e7',
    messagingSenderId: '64446242342',
    projectId: 'ssmachat',
    storageBucket: 'ssmachat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJwNOmpMA2uKreKeoCdx8vrxSeZUfVRg',
    appId: '1:64446242342:ios:ac02a762be552c316fd0e7',
    messagingSenderId: '64446242342',
    projectId: 'ssmachat',
    storageBucket: 'ssmachat.appspot.com',
    iosBundleId: 'com.example.videoConferenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJwNOmpMA2uKreKeoCdx8vrxSeZUfVRg',
    appId: '1:64446242342:ios:ac02a762be552c316fd0e7',
    messagingSenderId: '64446242342',
    projectId: 'ssmachat',
    storageBucket: 'ssmachat.appspot.com',
    iosBundleId: 'com.example.videoConferenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq-ckYxWFlUDnOjbO2ZtJiVoPi9OcTaR4',
    appId: '1:64446242342:web:6d845ad411fca22d6fd0e7',
    messagingSenderId: '64446242342',
    projectId: 'ssmachat',
    authDomain: 'ssmachat.firebaseapp.com',
    storageBucket: 'ssmachat.appspot.com',
  );

}